
services:
  db:
    image: postgres:16-alpine
    container_name: learnlang-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-learnlang}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-learnlang}
      POSTGRES_DB: ${POSTGRES_DB:-learnlang}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-learnlang} -d ${POSTGRES_DB:-learnlang}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
